# .github/workflows/build.yml
name: build-win

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-2022

    steps:
      # 1 ▸ исходники
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2 ▸ Node + npm-кэш
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3 ▸ Каталог, куда Electron-Forge кладёт билд
      - name: Ensure build directory exists
        shell: pwsh
        run: New-Item -ItemType Directory -Force -Path 'C:\builds\electron'

      # 4 ▸ Установка зависимостей (чисто, без post-install-скриптов)
      - name: Install dependencies (clean)
        run: npm ci --ignore-scripts

      # 5 ▸ Сборка установщика
      - name: Make Windows installer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run make

      # 6 ▸ Показать дерево результатов (не ломаем workflow, если каталога нет)
      - name: Show build folder tree
        shell: pwsh
        continue-on-error: true
        run: |
          if (Test-Path 'C:\builds\electron') {
            Get-ChildItem 'C:\builds\electron' -Recurse | Select-Object FullName
          } else {
            Write-Warning '⚠️  C:\builds\electron not found'
          }

      # 7 ▸ Загрузка артефактов
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: planhub_build_win
          path: 'C:\builds\electron\**\*'
          if-no-files-found: error
