# .github/workflows/build.yml
name: Build Windows exe

on:
  push:               # автоматически на каждый push
  workflow_dispatch:  # и вручную из «Actions»

jobs:
  build-win:
    runs-on: windows-latest        # Windows Server 2022

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2. Node + npm-cache
      - name: Set up Node 20 (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm ci --ignore-scripts

      # 4. Сборка installer’а
      - name: Build installer (Electron-Forge make)
        run: npm run make
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 4-bis. Выводим структуру каталога сборки (для отладки)
      - name: Show build directory
        run: dir C:\builds\electron /S /B

      # 5. Загружаем exe в artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: planhub-installer
          path: |
            C:/builds/electron/**/Setup.exe
            C:/builds/electron/**/PlanHub*Installer.exe
          if-no-files-found: error
