# .github/workflows/build.yml
name: build-win

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-2022

    steps:
      # 1 ▸ исходники
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2 ▸ Node + npm-кэш
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3 ▸ Установка зависимостей (чисто, без post-install)
      - name: Install dependencies
        run: npm ci --ignore-scripts

      # 4 ▸ Сборка (Electron-Forge → Squirrel-установщик)
      - name: Make Windows installer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run make

      # 5 ▸ Показать структуру каталога out/make
      - name: Show make folder tree
        shell: pwsh
        run: |
          if (Test-Path '.\out\make') {
            Get-ChildItem '.\out\make' -Recurse | Select-Object FullName
          } else {
            Write-Warning '⚠️  .\out\make not found'
          }

      # 6 ▸ Загрузка артефактов
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: planhub_build_win
          path: out/make/**/*
          if-no-files-found: error
