# .github/workflows/build.yml
name: build-win

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (clean)
        run: npm ci --ignore-scripts

      - name: Make Windows installer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run make

      # ▸▸ вместо cmd/dir используем PowerShell-листинг
      - name: Show build folder tree
        shell: pwsh
        run: |
          Get-ChildItem 'C:\builds\electron' -Recurse |
          Select-Object FullName

      # ▸▸ выгружаем всё, что появилось в C:\builds\electron
      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: planhub_build_win
          path: C:\builds\electron
